# Generated by Django 5.1.7 on 2026-04-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='comensales',
        ),
        migrations.AddField(
            model_name='comanda',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='nombre_cliente',
            field=models.CharField(default='Cliente General', max_length=100, verbose_name='Nombre del Cliente'),
            preserve_default=False,
        ),
    ]
