# Generated by Django 5.1.7 on 2026-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_comanda_comensales_comanda_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clave',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
