# Generated by Django 6.0.4 on 2026-04-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_producto_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecomanda',
            name='notas',
            field=models.CharField(blank=True, help_text='Ej: Sin azúcar, Alérgico a la lactosa', max_length=200, null=True),
        ),
    ]
