# Generated by Django 6.0.4 on 2026-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_detallecomanda_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecomanda',
            name='notas',
            field=models.CharField(blank=True, help_text='Ej: Sin azúcar', max_length=200, null=True),
        ),
    ]
