# Generated by Django 6.0.4 on 2026-05-05 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_proveedor_notas_alter_comanda_total_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_ideal',
            field=models.IntegerField(default=0, help_text='Cantidad óptima a mantener en bodega'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='gestion.proveedor'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(max_length=50),
        ),
    ]
