# Generated by Django 5.1.7 on 2026-05-05 02:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_insumo_stock_ideal_alter_insumo_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradainventario',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='La cantidad de entrada debe ser positiva.')]),
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='comentario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El stock actual no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_ideal',
            field=models.IntegerField(default=0, help_text='Cantidad óptima a mantener en bodega', validators=[django.core.validators.MinValueValidator(0, message='El stock ideal no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El stock mínimo no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio debe ser un valor positivo.')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='El correo electrónico debe ser de dominio @gmail.com.', regex='^[a-zA-Z0-9._%+-]+@gmail\\.com$')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 8 dígitos numéricos.', regex='^\\d{8}$')]),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_a_agregar', models.PositiveIntegerField(default=0, help_text='Cantidad que entra a bodega')),
                ('cantidad_a_quitar', models.PositiveIntegerField(default=0, help_text='Cantidad que sale o se usa')),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.insumo')),
            ],
        ),
    ]
