# Generated by Django 5.1.7 on 2026-05-05 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20260504_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradainventario',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad de entrada debe ser al menos 1.')]),
        ),
    ]
