# Generated by Django 5.1.7 on 2026-05-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_entradainventario_cantidad_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE gestion_entradainventario SET cantidad = GREATEST(cantidad, 1);",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
