# Generated by Django 5.1.7 on 2026-05-05 02:33

from django.db import migrations, models


def migrate_insumos_to_many_to_many(apps, schema_editor):
    Proveedor = apps.get_model('gestion', 'Proveedor')
    Insumo = apps.get_model('gestion', 'Insumo')
    
    for insumo in Insumo.objects.filter(proveedor__isnull=False):
        insumo.proveedor.insumos.add(insumo)


def reverse_migrate_insumos(apps, schema_editor):
    # No es necesario revertir, ya que la ForeignKey sigue ahí
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_producto_nombre_alter_proveedor_nombre_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='insumos',
            field=models.ManyToManyField(blank=True, help_text='Insumos que vende este proveedor', related_name='proveedores', to='gestion.insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='insumos_legacy', to='gestion.proveedor'),
        ),
        migrations.RunPython(migrate_insumos_to_many_to_many, reverse_migrate_insumos),
    ]
